export const minecraftItems = [
    'Acacia Leaves',
    'Acacia Log',
    'Acacia Planks',
    'Acacia Sapling',
    'Activator Rail',
    'Air',
    'Allium',
    'Ancient Debris',
    'Andesite',
    'Andesite Slab',
    'Andesite Stairs',
    'Andesite Wall',
    'Anvil',
    'Apple',
    'Armor Stand',
    'Arrow',
    'Azure Bluet',
    'Baked Potato',
    'Bamboo',
    'Barrel',
    'Barrier',
    'Basalt',
    'Beacon',
    'Bed',
    'Bedrock',
    'Beehive',
    'Beetroot',
    'Beetroot Seeds',
    'Beetroot Soup',
    'Bell',
    'Birch Boat',
    'Birch Button',
    'Birch Door',
    'Birch Fence',
    'Birch Fence Gate',
    'Birch Leaves',
    'Birch Log',
    'Birch Planks',
    'Birch Pressure Plate',
    'Birch Sapling',
    'Birch Sign',
    'Birch Slab',
    'Birch Stairs',
    'Birch Trapdoor',
    'Birch Wall Sign',
    'Birch Wood',
    'Black Banner',
    'Black Bed',
    'Black Carpet',
    'Black Concrete',
    'Black Concrete Powder',
    'Black Glazed Terracotta',
    'Black Shulker Box',
    'Black Stained Glass',
    'Black Stained Glass Pane',
    'Black Terracotta',
    'Black Wool',
    'Blackstone',
    'Blackstone Slab',
    'Blackstone Stairs',
    'Blackstone Wall',
    'Blast Furnace',
    'Blaze Powder',
    'Blaze Rod',
    'Blaze Spawn Egg',
    'Blue Banner',
    'Blue Bed',
    'Blue Carpet',
    'Blue Concrete',
    'Blue Concrete Powder',
    'Blue Glazed Terracotta',
    'Blue Ice',
    'Blue Orchid',
    'Blue Shulker Box',
    'Blue Stained Glass',
    'Blue Stained Glass Pane',
    'Blue Terracotta',
    'Blue Wool',
    'Bone',
    'Bone Block',
    'Bone Meal',
    'Book',
    'Bookshelf',
    'Bow',
    'Bowl',
    'Brain Coral',
    'Brain Coral Block',
    'Brain Coral Fan',
    'Brain Coral Wall Fan',
    'Bread',
    'Brewing Stand',
    'Brick',
    'Brick Slab',
    'Brick Stairs',
    'Brick Wall',
    'Bricks',
    'Brown Banner',
    'Brown Bed',
    'Brown Carpet',
    'Brown Concrete',
    'Brown Concrete Powder',
    'Brown Glazed Terracotta',
    'Brown Mushroom',
    'Brown Mushroom Block',
    'Brown Shulker Box',
    'Brown Stained Glass',
    'Brown Stained Glass Pane',
    'Brown Terracotta',
    'Brown Wool',
    'Bubble Column',
    'Bubble Coral',
    'Bubble Coral Block',
    'Bubble Coral Fan',
    'Bubble Coral Wall Fan',
    'Bucket',
    'Cactus',
    'Cake',
    'Campfire',
    'Carrot',
    'Carrot on a Stick',
    'Cartography Table',
    'Carved Pumpkin',
    'Cauldron',
    'Cave Air',
    'Cave Spider Spawn Egg',
    'Chain',
    'Chain Command Block',
    'Chainmail Boots',
    'Chainmail Chestplate',
    'Chainmail Helmet',
    'Chainmail Leggings',
    'Charcoal',
    'Chest',
    'Chest Minecart',
    'Chicken',
    'Chicken Spawn Egg',
    'Chipped Anvil',
    'Chiseled Nether Bricks',
    'Chiseled Polished Blackstone',
    'Chiseled Quartz Block',
    'Chiseled Red Sandstone',
    'Chiseled Sandstone',
    'Chiseled Stone Bricks',
    'Chorus Flower',
    'Chorus Fruit',
    'Chorus Plant',
    'Clay',
    'Clay Ball',
    'Clock',
    'Coal',
    'Coal Block',
    'Coal Ore',
    'Coarse Dirt',
    'Cobblestone',
    'Cobblestone Slab',
    'Cobblestone Stairs',
    'Cobblestone Wall',
    'Cobweb',
    'Cocoa Beans',
    'Cod',
    'Cod Bucket',
    'Cod Spawn Egg',
    'Command Block',
    'Command Block Minecart',
    'Compass',
    'Composter',
    'Conduit',
    'Cooked Beef',
    'Cooked Chicken',
    'Cooked Cod',
    'Cooked Mutton',
    'Cooked Porkchop',
    'Cooked Rabbit',
    'Cooked Salmon',
    'Cookie',
    'Cornflower',
    'Cow Spawn Egg',
    'Cracked Nether Bricks',
    'Cracked Polished Blackstone Bricks',
    'Cracked Stone Bricks',
    'Crafting Table',
    'Creeper Head',
    'Creeper Spawn Egg',
    'Crimson Button',
    'Crimson Door',
    'Crimson Fence',
    'Crimson Fence Gate',
    'Crimson Fungus',
    'Crimson Hyphae',
    'Crimson Nylium',
    'Crimson Planks',
    'Crimson Pressure Plate',
    'Crimson Roots',
    'Crimson Sign',
    'Crimson Slab',
    'Crimson Stairs',
    'Crimson Stem',
    'Crimson Trapdoor',
    'Crimson Wall Sign',
    'Crossbow',
    'Crying Obsidian',
    'Cut Red Sandstone',
    'Cut Red Sandstone Slab',
    'Cut Sandstone',
    'Cut Sandstone Slab',
    'Cyan Banner',
    'Cyan Bed',
    'Cyan Carpet',
    'Cyan Concrete',
    'Cyan Concrete Powder',
    'Cyan Glazed Terracotta',
    'Cyan Shulker Box',
    'Cyan Stained Glass',
    'Cyan Stained Glass Pane',
    'Cyan Terracotta',
    'Cyan Wool',
    'Damaged Anvil',
    'Dandelion',
    'Dandelion Yellow',
    'Dark Oak Boat',
    'Dark Oak Button',
    'Dark Oak Door',
    'Dark Oak Fence',
    'Dark Oak Fence Gate',
    'Dark Oak Leaves',
    'Dark Oak Log',
    'Dark Oak Planks',
    'Dark Oak Pressure Plate',
    'Dark Oak Sapling',
    'Dark Oak Sign',
    'Dark Oak Slab',
    'Dark Oak Stairs',
    'Dark Oak Trapdoor',
    'Dark Oak Wall Sign',
    'Dark Oak Wood',
    'Dark Prismarine',
    'Dark Prismarine Slab',
    'Dark Prismarine Stairs',
    'Daylight Detector',
    'Dead Brain Coral',
    'Dead Brain Coral Block',
    'Dead Brain Coral Fan',
    'Dead Brain Coral Wall Fan',
    'Dead Bubble Coral',
    'Dead Bubble Coral Block',
    'Dead Bubble Coral Fan',
    'Dead Bubble Coral Wall Fan',
    'Dead Bush',
    'Dead Fire Coral',
    'Dead Fire Coral Block',
    'Dead Fire Coral Fan',
    'Dead Fire Coral Wall Fan',
    'Dead Horn Coral',
    'Dead Horn Coral Block',
    'Dead Horn Coral Fan',
    'Dead Horn Coral Wall Fan',
    'Dead Tube Coral',
    'Dead Tube Coral Block',
    'Dead Tube Coral Fan',
    'Dead Tube Coral Wall Fan',
    'Detector Rail',
    'Diamond',
    'Diamond Axe',
    'Diamond Block',
    'Diamond Boots',
    'Diamond Chestplate',
    'Diamond Helmet',
    'Diamond Hoe',
    'Diamond Horse Armor',
    'Diamond Leggings',
    'Diamond Ore',
    'Diamond Pickaxe',
    'Diamond Shovel',
    'Diamond Sword',
    'Diorite',
    'Diorite Slab',
    'Diorite Stairs',
    'Diorite Wall',
    'Dirt',
    'Dispenser',
    'Dolphin Spawn Egg',
    'Donkey Spawn Egg',
    'Dragon Breath',
    'Dragon Egg',
    'Dragon Head',
    'Dried Kelp',
    'Dried Kelp Block',
    'Dropper',
    'Drowned Spawn Egg',
    'Egg',
    'Elder Guardian Spawn Egg',
    'Elytra',
    'Emerald',
    'Emerald Block',
    'Emerald Ore',
    'Enchanted Book',
    'Enchanted Golden Apple',
    'Enchanting Table',
    'End Crystal',
    'End Gateway',
    'End Portal',
    'End Portal Frame',
    'End Rod',
    'End Stone',
    'End Stone Brick Slab',
    'End Stone Brick Stairs',
    'End Stone Brick Wall',
    'End Stone Bricks',
    'Ender Chest',
    'Ender Eye',
    'Ender Pearl',
    'Enderman Spawn Egg',
    'Endermite Spawn Egg',
    'Evoker Spawn Egg',
    'Experience Bottle',
    'Farmland',
    'Feather',
    'Fermented Spider Eye',
    'Fern',
    'Filled Map',
    'Fire',
    'Fire Charge',
    'Fire Coral',
    'Fire Coral Block',
    'Fire Coral Fan',
    'Fire Coral Wall Fan',
    'Firework Rocket',
    'Firework Star',
    'Fishing Rod',
    'Fletching Table',
    'Flint',
    'Flint and Steel',
    'Flower Pot',
    'Furnace',
    'Furnace Minecart',
    'Ghast Spawn Egg',
    'Ghast Tear',
    'Gilded Blackstone',
    'Glass',
    'Glass Bottle',
    'Glass Pane',
    'Glistering Melon Slice',
    'Globe Banner Pattern',
    'Glow Berries',
    'Glow Ink Sac',
    'Glow Item Frame',
    'Glow Lichen',
    'Glowstone',
    'Glowstone Dust',
    'Goat Horn',
    'Goat Spawn Egg',
    'Gold Block',
    'Gold Ingot',
    'Gold Nugget',
    'Gold Ore',
    'Golden Apple',
    'Golden Axe',
    'Golden Boots',
    'Golden Carrot',
    'Golden Chestplate',
    'Golden Helmet',
    'Golden Hoe',
    'Golden Horse Armor',
    'Golden Leggings',
    'Golden Pickaxe',
    'Golden Shovel',
    'Golden Sword',
    'Granite',
    'Granite Slab',
    'Granite Stairs',
    'Granite Wall',
    'Grass',
    'Grass Block',
    'Grass Path',
    'Gravel',
    'Gray Banner',
    'Gray Bed',
    'Gray Carpet',
    'Gray Concrete',
    'Gray Concrete Powder',
    'Gray Glazed Terracotta',
    'Gray Shulker Box',
    'Gray Stained Glass',
    'Gray Stained Glass Pane',
    'Gray Terracotta',
    'Gray Wool',
    'Green Banner',
    'Green Bed',
    'Green Carpet',
    'Green Concrete',
    'Green Concrete Powder',
    'Green Glazed Terracotta',
    'Green Shulker Box',
    'Green Stained Glass',
    'Green Stained Glass Pane',
    'Green Terracotta',
    'Green Wool',
    'Grindstone',
    'Guardian Spawn Egg',
    'Gunpowder',
    'Hay Bale',
    'Heart of the Sea',
    'Heavy Weighted Pressure Plate',
    'Hoglin Spawn Egg',
    'Honey Block',
    'Honey Bottle',
    'Honeycomb',
    'Honeycomb Block',
    'Hopper',
    'Hopper Minecart',
    'Horn Coral',
    'Horn Coral Block',
    'Horn Coral Fan',
    'Horn Coral Wall Fan',
    'Horse Spawn Egg',
    'Husk Spawn Egg',
    'Ice',
    'Infested Chiseled Stone Bricks',
    'Infested Cobblestone',
    'Infested Cracked Stone Bricks',
    'Infested Mossy Stone Bricks',
    'Infested Stone',
    'Infested Stone Bricks',
    'Ink Sac',
    'Iron Axe',
    'Iron Bars',
    'Iron Block',
    'Iron Boots',
    'Iron Chestplate',
    'Iron Door',
    'Iron Helmet',
    'Iron Hoe',
    'Iron Horse Armor',
    'Iron Ingot',
    'Iron Leggings',
    'Iron Nugget',
    'Iron Ore',
    'Iron Pickaxe',
    'Iron Shovel',
    'Iron Sword',
    'Iron Trapdoor',
    'Item Frame',
    'Jack o\'Lantern',
    'Jigsaw Block',
    'Jukebox',
    'Jungle Boat',
    'Jungle Button',
    'Jungle Door',
    'Jungle Fence',
    'Jungle Fence Gate',
    'Jungle Leaves',
    'Jungle Log',
    'Jungle Planks',
    'Jungle Pressure Plate',
    'Jungle Sapling',
    'Jungle Sign',
    'Jungle Slab',
    'Jungle Stairs',
    'Jungle Trapdoor',
    'Jungle Wall Sign',
    'Jungle Wood',
    'Kelp',
    'Knowledge Book',
    'Ladder',
    'Lantern',
    'Lapis Lazuli',
    'Lapis Lazuli Block',
    'Lapis Lazuli Ore',
    'Large Fern',
    'Lava',
    'Lava Bucket',
    'Lead',
    'Leather',
    'Leather Boots',
    'Leather Cap',
    'Leather Horse Armor',
    'Leather Pants',
    'Leather Tunic',
    'Lectern',
    'Lever',
    'Light Blue Banner',
    'Light Blue Bed',
    'Light Blue Carpet',
    'Light Blue Concrete',
    'Light Blue Concrete Powder',
    'Light Blue Glazed Terracotta',
    'Light Blue Shulker Box',
    'Light Blue Stained Glass',
    'Light Blue Stained Glass Pane',
    'Light Blue Terracotta',
    'Light Blue Wool',
    'Light Gray Banner',
    'Light Gray Bed',
    'Light Gray Carpet',
    'Light Gray Concrete',
    'Light Gray Concrete Powder',
    'Light Gray Glazed Terracotta',
    'Light Gray Shulker Box',
    'Light Gray Stained Glass',
    'Light Gray Stained Glass Pane',
    'Light Gray Terracotta',
    'Light Gray Wool',
    'Light Weighted Pressure Plate',
    'Lilac',
    'Lily Pad',
    'Lily of the Valley',
    'Lime Banner',
    'Lime Bed',
    'Lime Carpet',
    'Lime Concrete',
    'Lime Concrete Powder',
    'Lime Glazed Terracotta',
    'Lime Shulker Box',
    'Lime Stained Glass',
    'Lime Stained Glass Pane',
    'Lime Terracotta',
    'Lime Wool',
    'Lingering Potion',
    'Llama Spawn Egg',
    'Lodestone',
    'Magenta Banner',
    'Magenta Bed',
    'Magenta Carpet',
    'Magenta Concrete',
    'Magenta Concrete Powder',
    'Magenta Glazed Terracotta',
    'Magenta Shulker Box',
    'Magenta Stained Glass',
    'Magenta Stained Glass Pane',
    'Magenta Terracotta',
    'Magenta Wool',
    'Magma Block',
    'Magma Cream',
    'Magma Cube Spawn Egg',
    'Map',
    'Melon',
    'Melon Seeds',
    'Melon Slice',
    'Milk Bucket',
    'Minecart',
    'Mooshroom Spawn Egg',
    'Mossy Cobblestone',
    'Mossy Cobblestone Slab',
    'Mossy Cobblestone Stairs',
    'Mossy Cobblestone Wall',
    'Mossy Stone Bricks',
    'Mossy Stone Brick Slab',
    'Mossy Stone Brick Stairs',
    'Mossy Stone Brick Wall',
    'Mule Spawn Egg',
    'Mushroom Stem',
    'Mushroom Stew',
    'Music Disc - 11',
    'Music Disc - 13',
    'Music Disc - Blocks',
    'Music Disc - Cat',
    'Music Disc - Chirp',
    'Music Disc - Far',
    'Music Disc - Mall',
    'Music Disc - Mellohi',
    'Music Disc - Pigstep',
    'Music Disc - Stal',
    'Music Disc - Strad',
    'Music Disc - Wait',
    'Music Disc - Ward',
    'Mycelium',
    'Name Tag',
    'Nautilus Shell',
    'Netherite Axe',
    'Netherite Block',
    'Netherite Boots',
    'Netherite Chestplate',
    'Netherite Helmet',
    'Netherite Hoe',
    'Netherite Ingot',
    'Netherite Leggings',
    'Netherite Pickaxe',
    'Netherite Scrap',
    'Netherite Shovel',
    'Netherite Sword',
    'Netherrack',
    'Note Block',
    'Oak Boat',
    'Oak Button',
    'Oak Door',
    'Oak Fence',
    'Oak Fence Gate',
    'Oak Leaves']